#!/usr/bin/env node
// The reaction store's schema, generated from the app's own vocabulary.
//
// Generated rather than written down. The table constrains three things the
// app also enforces — which reasons exist, which reactions exist, and what a
// slug looks like — and a hand-copied schema drifts the moment one of them is
// renamed. When it drifts the database rejects rows the app still sends, and
// because a failed insert is deliberately swallowed in the browser, the
// feedback disappears with nothing to notice.
//
// Print it with:
//   node scripts/reaction-store-schema.ts
import { pathToFileURL } from 'node:url';
import { DISLIKE_REASONS, REACTION_KINDS, SLUG_PATTERN } from '#lib/reaction-types.ts';

/**
 * Rows one slug may collect in a minute before the store refuses further
 * inserts. Generous for a hobby site: it bounds abuse without capping a
 * genuinely popular day.
 */
export const MAX_INSERTS_PER_SLUG_PER_MINUTE = 60;

/** Renders `['a', 'b']` as the SQL literal list `'a','b'`. */
function sqlList(values: readonly string[]): string {
  return values.map((value) => `'${value.replaceAll("'", "''")}'`).join(',');
}

/**
 * DDL for the reaction table, its constraints, its RLS policy and the trigger
 * that rate-limits inserts.
 *
 * The `anon` key ships in the page, so anyone who loads the site can post
 * to this table. These constraints — not the checks in the browser — are
 * what actually bound what can be stored.
 *
 * @param reasons Overridden only by tests; defaults to the real vocabulary.
 */
export function buildReactionStoreDdl(
  reasons: readonly {
    readonly id: string;
    readonly label: string;
  }[] = DISLIKE_REASONS,
): string {
  return `-- Generated by scripts/reaction-store-schema.ts — do not edit by hand.
create table public.reactions (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  slug        text not null check (slug ~ '${SLUG_PATTERN.source}'),
  reaction    text not null check (reaction in (${sqlList([...REACTION_KINDS])})),
  reasons     text[] not null default '{}'
              check (reasons <@ array[${sqlList(reasons.map((reason) => reason.id))}])
              check (cardinality(reasons) <= ${reasons.length})
);

-- The leading column still serves slug lookups; created_at bounds the rate
-- limit's count to the rows inside its window rather than every row the slug
-- has ever collected.
create index reactions_slug_created_at_idx on public.reactions (slug, created_at);

alter table public.reactions enable row level security;

-- The key that ships in the page may insert, and do nothing else. The
-- front-end never reads, so a select that returns rows means the
-- policy is wrong. RLS with no select policy answers 200 with an empty
-- array, not an error.
create policy "anon may insert one reaction"
  on public.reactions for insert to anon with check (true);

-- That policy admits any row, so this is what bounds how fast one game can
-- collect them. The tally already tolerates junk, so the limit is abuse
-- resistance, not correctness.
--
-- security definer is load-bearing: the count reads public.reactions, and the
-- inserting key has no select policy, so an invoker-rights function would
-- count zero every time and the limit would never fire.
--
-- The count is a snapshot, so inserts racing each other can each see room and
-- carry a window a few rows past the cap. The limit is a bound on the rate,
-- not an exact ceiling on the window.
create or replace function public.reactions_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (
    select count(*)
      from public.reactions
     where slug = new.slug
       and created_at > now() - interval '1 minute'
  ) >= ${MAX_INSERTS_PER_SLUG_PER_MINUTE} then
    raise exception 'too many reactions for % in one minute', new.slug
      using errcode = 'check_violation';
  end if;
  return new;
end;
$$;

create trigger reactions_rate_limit
  before insert on public.reactions
  for each row execute function public.reactions_rate_limit();
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  console.log(buildReactionStoreDdl());
}
