#!/usr/bin/env node
// The reaction store's schema, generated from the app's own vocabulary.
//
// Generated rather than written down. The table constrains three things the
// app also enforces — which reasons exist, which reactions exist, and what a
// slug looks like — and a hand-copied schema drifts the moment one of them is
// renamed. When it drifts the database rejects rows the app still sends, and
// because a failed insert is deliberately swallowed in the browser, the
// feedback disappears with nothing to notice.
//
// Print it with:
//   node --experimental-strip-types scripts/reaction-store-schema.ts
import { pathToFileURL } from 'node:url';
import {
  DISLIKE_REASONS,
  REACTION_KINDS,
  SLUG_PATTERN,
  type DislikeReason,
} from '#lib/reaction-types.ts';

/** Renders `['a', 'b']` as the SQL literal list `'a','b'`. */
function sqlList(values: readonly string[]): string {
  return values.map((value) => `'${value.replaceAll("'", "''")}'`).join(',');
}

/**
 * DDL for the reaction table, its constraints and its RLS policy.
 *
 * The `anon` key ships in the page, so anyone who loads the site can post
 * to this table. These constraints — not the checks in the browser — are
 * what actually bound what can be stored.
 *
 * @param reasons Overridden only by tests; defaults to the real vocabulary.
 */
export function buildReactionStoreDdl(
  reasons: readonly { readonly id: DislikeReason | string; readonly label: string }[] = DISLIKE_REASONS,
): string {
  return `-- Generated by scripts/reaction-store-schema.ts — do not edit by hand.
create table public.reactions (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  slug        text not null check (slug ~ '${SLUG_PATTERN.source}'),
  reaction    text not null check (reaction in (${sqlList([...REACTION_KINDS])})),
  reasons     text[] not null default '{}'
              check (reasons <@ array[${sqlList(reasons.map((reason) => reason.id))}])
);

alter table public.reactions enable row level security;

-- The key that ships in the page may insert, and do nothing else. The
-- front-end never reads, so a select that returns rows means the
-- policy is wrong. RLS with no select policy answers 200 with an empty
-- array, not an error.
create policy "anon may insert one reaction"
  on public.reactions for insert to anon with check (true);
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  console.log(buildReactionStoreDdl());
}
