#!/usr/bin/env node
// The reaction store's schema, generated from the app's own vocabulary.
//
// Generated rather than written down. The table constrains three things the
// app also enforces — which reasons exist, which reactions exist, and what a
// slug looks like — and a hand-copied schema drifts the moment one of them is
// renamed. When it drifts the database rejects rows the app still sends, and
// because a failed insert is deliberately swallowed in the browser, the
// feedback disappears with nothing to notice.
//
// Print it with:
//   node scripts/reaction-store-schema.ts
import { pathToFileURL } from 'node:url';
import { DISLIKE_REASONS, REACTION_KINDS, SLUG_PATTERN } from '#lib/reaction-types.ts';

/**
 * Rows one slug may collect in a minute before the store refuses further
 * inserts. Generous for a hobby site: it bounds abuse without capping a
 * genuinely popular day.
 */
export const MAX_INSERTS_PER_SLUG_PER_MINUTE = 60;

/** Renders `['a', 'b']` as the SQL literal list `'a','b'`. */
function sqlList(values: readonly string[]): string {
  return values.map((value) => `'${value.replaceAll("'", "''")}'`).join(',');
}

/**
 * DDL for the reaction table, its constraints, its RLS policy, the trigger
 * that rate-limits inserts, and the aggregate view the pipeline reads.
 *
 * The `anon` key ships in the page, so anyone who loads the site can post
 * to this table. These constraints — not the checks in the browser — are
 * what actually bound what can be stored.
 *
 * @param reasons Overridden only by tests; defaults to the real vocabulary.
 */
export function buildReactionStoreDdl(
  reasons: readonly {
    readonly id: string;
    readonly label: string;
  }[] = DISLIKE_REASONS,
): string {
  // Built as one list so the separator sits between columns rather than after
  // each: an empty vocabulary would otherwise leave a comma before `from`.
  const countColumns = [
    `count(*) filter (where reaction = 'like')    as likes`,
    `count(*) filter (where reaction = 'dislike') as dislikes`,
    ...reasons.map(
      (reason) =>
        `count(*) filter (where reaction = 'dislike' and ${sqlList([reason.id])} = any (reasons)) as "${reason.id}"`,
    ),
  ]
    .map((column) => `  ${column}`)
    .join(',\n');

  return `-- Generated by scripts/reaction-store-schema.ts — do not edit by hand.
create table public.reactions (
  id          bigint generated always as identity primary key,
  created_at  timestamptz not null default now(),
  slug        text not null check (slug ~ '${SLUG_PATTERN.source}'),
  reaction    text not null check (reaction in (${sqlList([...REACTION_KINDS])})),
  reasons     text[] not null default '{}'
              check (reasons <@ array[${sqlList(reasons.map((reason) => reason.id))}])
              check (cardinality(reasons) <= ${reasons.length})
);

-- The leading column still serves slug lookups; created_at bounds the rate
-- limit's count to the rows inside its window rather than every row the slug
-- has ever collected.
create index reactions_slug_created_at_idx on public.reactions (slug, created_at);

alter table public.reactions enable row level security;

-- The key that ships in the page may insert, and do nothing else. The
-- front-end never reads, so a select that returns rows means the
-- policy is wrong. RLS with no select policy answers 200 with an empty
-- array, not an error.
create policy "anon may insert one reaction"
  on public.reactions for insert to anon with check (true);

-- That policy admits any row, so the two triggers below are what bound how
-- fast one game can collect them. The tally already tolerates junk, so the
-- limit is abuse resistance, not correctness.

-- The policy admits any column, not just the ones the page sends, so a caller
-- can supply its own created_at. Stamping it is what makes the window in the
-- limit mean anything: rows dated last year would otherwise never be counted
-- and the cap would never fire. Only a before-row trigger can set it.
create or replace function public.reactions_stamp_insert_time()
returns trigger
language plpgsql
as $$
begin
  new.created_at := now();
  return new;
end;
$$;

create trigger reactions_stamp_insert_time
  before insert on public.reactions
  for each row execute function public.reactions_stamp_insert_time();

-- Runs once per statement, over the whole batch. A row-level check cannot do
-- this job: one POST may carry an array of rows, and a before-row trigger
-- sees neither the rows inserted beside it in the same statement nor how many
-- are coming, so every row of a batch counts the same total and the batch
-- lands whole.
--
-- security definer is load-bearing: the count reads public.reactions, and the
-- inserting key has no select policy, so an invoker-rights function would
-- count zero every time and the limit would never fire.
create or replace function public.reactions_rate_limit()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  offender text;
begin
  -- Serialises inserts per slug. Without it each concurrent transaction counts
  -- the same committed rows, every one of them finds room, and a burst lands
  -- in full however low the cap. Ordered so two batches touching the same
  -- slugs cannot take them in opposite orders. Released at transaction end.
  perform pg_advisory_xact_lock(hashtext(slug)::bigint)
     from (select distinct slug from new_rows order by slug) s;

  -- An after-statement trigger sees the rows the statement inserted, so this
  -- count already includes them and the cap is the size of the window rather
  -- than what preceded it.
  select s.slug into offender
    from (select distinct slug from new_rows) s
   where (
     select count(*)
       from public.reactions r
      where r.slug = s.slug
        and r.created_at > now() - interval '1 minute'
        -- A row stamped in the future predates these triggers and would sit
        -- in every window from now on, closing that slug permanently.
        and r.created_at <= now()
   ) > ${MAX_INSERTS_PER_SLUG_PER_MINUTE}
   limit 1;

  if offender is not null then
    raise exception 'too many reactions for % in one minute', offender
      using errcode = 'check_violation';
  end if;

  return null;
end;
$$;

create trigger reactions_rate_limit
  after insert on public.reactions
  referencing new table as new_rows
  for each statement execute function public.reactions_rate_limit();

-- One row per game, so the pipeline reads a tally instead of every row. The
-- reason columns come from the same vocabulary as the constraints above, so a
-- renamed reason renames its column with it.
-- security_invoker belongs in the create, not a statement after it. This DDL
-- is pasted in by hand and may not run in one transaction, and a view that
-- exists for even a moment with its owner's rights reads straight past the
-- row level security below.
create view public.reaction_counts with (security_invoker = on) as
select
  slug,
${countColumns}
from public.reactions
group by slug;

revoke all on public.reaction_counts from anon;
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  console.log(buildReactionStoreDdl());
}
